<?php

$currency_symbols = [
    'AUDCAD', 'AUDCHF', 'AUDDKK', 'AUDHKD', 'AUDHUF',
    'AUDJPY', 'AUDNOK', 'AUDNZD', 'AUDPLN', 'AUDSEK',
    'AUDSGD', 'AUDTRY', 'AUDUSD', 'CADCHF', 'CADHKD',
    'CADHUF', 'CADJPY', 'CADNOK', 'CADPLN', 'CADSEK',
    'CHFHKD', 'CHFHUF', 'CHFJPY', 'CHFNOK', 'CHFPLN',
    'CHFSEK', 'EURAUD', 'EURCAD', 'EURCHF', 'EURCZK',
    'EURDKK', 'EURGBP', 'EURHKD', 'EURHUF', 'EURJPY',
    'EURNOK', 'EURNZD', 'EURPLN', 'EURSEK', 'EURTRY',
    'EURUSD', 'GBPAUD', 'GBPCAD', 'GBPCHF', 'GBPDKK',
    'GBPHKD', 'GBPHUF', 'GBPJPY', 'GBPNOK', 'GBPPLN',
    'GBPSEK',  'GBPTRY',  'GBPUSD',  'USDCAD',  'USDCHF',
    'USDCZK',  'USDDKK',  'USDHKD',  'USDHUF',  'USDJPY',
    'USDMXN',  'USDNOK',  'USDPLN',  'USDSEK',  'USDSGD',
    'USDTRY',  'USDZAR'
];

$timeframes = ['M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1', 'MN'];

$currency_names = [
    'AUDCAD' => 'Australian Dollar vs Canadian Dollar',
    'AUDCHF' => 'Australian Dollar vs Swiss Franc',
    'AUDDKK' => 'Australian Dollar vs Danish Krone',
    'AUDHKD' => 'Australian Dollar vs Hong Kong Dollar',
    'AUDHUF' => 'Australian Dollar vs Hungarian Forint',
    'AUDJPY' => 'Australian Dollar vs Japanese Yen',
    'AUDNOK' => 'Australian Dollar vs Norwegian Krone',
    'AUDNZD' => 'Australian Dollar vs New Zealand Dollar',
    'AUDPLN' => 'Australian Dollar vs Polish Zloty',
    'AUDSEK' => 'Australian Dollar vs Swedish Krona',
    'AUDSGD' => 'Australian Dollar vs Singapore Dollar',
    'AUDTRY' => 'Australian Dollar vs Turkish Lira',
    'AUDUSD' => 'Australian Dollar vs United States Dollar',
    'CADCHF' => 'Canadian Dollar vs Swiss Franc',
    'CADHKD' => 'Canadian Dollar vs Hong Kong Dollar',
    'CADHUF' => 'Canadian Dollar vs Hungarian Forint',
    'CADJPY' => 'Canadian Dollar vs Japanese Yen',
    'CADNOK' => 'Canadian Dollar vs Norwegian Krone',
    'CADPLN' => 'Canadian Dollar vs Polish Zloty',
    'CADSEK' => 'Canadian Dollar vs Swedish Krona',
    'CHFHKD' => 'Swiss Franc vs Hong Kong Dollar',
    'CHFHUF' => 'Swiss Franc vs Hungarian Forint',
    'CHFJPY' => 'Swiss Franc vs Japanese Yen',
    'CHFNOK' => 'Swiss Franc vs Norwegian Krone',
    'CHFPLN' => 'Swiss Franc vs Polish Zloty',
    'CHFSEK' => 'Swiss Franc vs Swedish Krona',
    'EURAUD' => 'Euro vs Australian Dollar',
    'EURCAD' => 'Euro vs Canadian Dollar',
    'EURCHF' => 'Euro vs Swiss Franc',
    'EURCZK' => 'Euro vs Czech Koruna',
    'EURDKK' => 'Euro vs Danish Krone',
    'EURGBP' => 'Euro vs British Pound',
    'EURHKD' => 'Euro vs Hong Kong Dollar',
    'EURHUF' => 'Euro vs Hungarian Forint',
    'EURJPY' => 'Euro vs Japanese Yen',
    'EURNOK' => 'Euro vs Norwegian Krone',
    'EURNZD' => 'Euro vs New Zealand Dollar',
    'EURPLN' => 'Euro vs Polish Zloty',
    'EURSEK' => 'Euro vs Swedish Krona',
    'EURTRY' => 'Euro vs Turkish Lira',
    'EURUSD' => 'Euro vs United States Dollar',
    'GBPAUD' => 'British Pound vs Australian Dollar',
    'GBPCAD' => 'British Pound vs Canadian Dollar',
    'GBPCHF' => 'British Pound vs Swiss Franc',
    'GBPDKK' => 'British Pound vs Danish Krone',
    'GBPHKD' => 'British Pound vs Hong Kong Dollar',
    'GBPHUF' => 'British Pound vs Hungarian Forint',
    'GBPJPY' => 'British Pound vs Japanese Yen',
    'GBPNOK' => 'British Pound vs Norwegian Krone',
    'GBPPLN' => 'British Pound vs Polish Zloty',
    'GBPSEK' => 'British Pound vs Swedish Krona',
    'GBPTRY' => 'British Pound vs Turkish Lira',
    'GBPUSD' => 'British Pound vs United States Dollar',
    'USDCAD' => 'United States Dollar vs Canadian Dollar',
    'USDCHF' => 'United States Dollar vs Swiss Franc',
    'USDCZK' => 'United States Dollar vs Czech Koruna',
    'USDDKK' => 'United States Dollar vs Danish Krone',
    'USDHKD' => 'United States Dollar vs Hong Kong Dollar',
    'USDHUF' => 'United States Dollar vs Hungarian Forint',
    'USDJPY' => 'United States Dollar vs Japanese Yen',
    'USDMXN' => 'United States Dollar vs Mexican Peso',
    'USDNOK' => 'United States Dollar vs Norwegian Krone',
    'USDPLN' => 'United States Dollar vs Polish Zloty',
    'USDSEK' => 'United States Dollar vs Swedish Krona',
    'USDSGD' => 'United States Dollar vs Singapore Dollar',
    'USDTRY' => 'United States Dollar vs Turkish Lira',
    'USDZAR' => 'United States Dollar vs South African Rand',
];

$account = [
    'balance' => 100000.00,
    'equity' => 99999.89,
    'margin' => 13.03,
    'free_margin' => 99986.86,
    'level' => 767458.866
];

$currency_pairs = [
    ['symbol' => 'AUDCAD', 'bid' => 0.91162, 'ask' => 0.91175, 'change' => 0.41, 'direction' => 'up'],
    ['symbol' => 'AUDCHF', 'bid' => 0.51828, 'ask' => 0.51841, 'change' => 0.41, 'direction' => 'down'],
    ['symbol' => 'AUDDKK', 'bid' => 4.45852, 'ask' => 4.46016, 'change' => 0, 'direction' => 'neutral'],
    ['symbol' => 'AUDHKD', 'bid' => 5.25944, 'ask' => 5.25953, 'change' => 0, 'direction' => 'neutral'],
    ['symbol' => 'AUDHUF', 'bid' => 228.86992, 'ask' => 229.08708, 'change' => 0, 'direction' => 'neutral'],
    ['symbol' => 'AUDJPY', 'bid' => 99.435, 'ask' => 99.448, 'change' => 0.89, 'direction' => 'up'],
    ['symbol' => 'AUDNOK', 'bid' => 6.89340, 'ask' => 6.89630, 'change' => 0, 'direction' => 'neutral'],
    ['symbol' => 'AUDNZD', 'bid' => 1.13246, 'ask' => 1.13273, 'change' => 0.21, 'direction' => 'up'],
    ['symbol' => 'AUDPLN', 'bid' => 2.63122, 'ask' => 2.63225, 'change' => 0, 'direction' => 'neutral'],
    ['symbol' => 'AUDSEK', 'bid' => 6.11812, 'ask' => 6.12610, 'change' => 0.46, 'direction' => 'up'],
];

$positions = [
    ['symbol' => 'AUDCAD', 'type' => 'buy', 'volume' => 0.02, 'open_price' => 0.91182, 'current_price' => 0.91174, 'profit' => -0.11]
];