<?php

$currency_symbols = [
    'EURUSD', 'AUDCAD', 'AUDCHF', 'AUDDKK', 'AUDHKD', 'AUDHUF',
    'AUDJPY', 'AUDNOK', 'AUDNZD', 'AUDPLN', 'AUDSEK',
    'AUDSGD', 'AUDTRY', 'AUDUSD', 'CADCHF', 'CADHKD',
    'CADHUF', 'CADJPY', 'CADNOK', 'CADPLN', 'CADSEK',
    'CHFHKD', 'CHFHUF', 'CHFJPY', 'CHFNOK', 'CHFPLN',
    'CHFSEK', 'EURAUD', 'EURCAD', 'EURCHF', 'EURCZK',
    'EURDKK', 'EURGBP', 'EURHKD', 'EURHUF', 'EURJPY',
    'EURNOK', 'EURNZD', 'EURPLN', 'EURSEK', 'EURTRY',
    'GBPAUD', 'GBPCAD', 'GBPCHF', 'GBPDKK',
    'GBPHKD', 'GBPHUF', 'GBPJPY', 'GBPNOK', 'GBPPLN',
    'GBPSEK',  'GBPTRY',  'GBPUSD',  'USDCAD',  'USDCHF',
    'USDCZK',  'USDDKK',  'USDHKD',  'USDHUF',  'USDJPY',
    'USDMXN',  'USDNOK',  'USDPLN',  'USDSEK',  'USDSGD',
    'USDTRY',  'USDZAR'
];

$timeframes = ['M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1', 'MN'];

$currency_names = [
    'AUDCAD' => 'Australian Dollar vs Canadian Dollar',
    'AUDCHF' => 'Australian Dollar vs Swiss Franc',
    'AUDDKK' => 'Australian Dollar vs Danish Krone',
    'AUDHKD' => 'Australian Dollar vs Hong Kong Dollar',
    'AUDHUF' => 'Australian Dollar vs Hungarian Forint',
    'AUDJPY' => 'Australian Dollar vs Japanese Yen',
    'AUDNOK' => 'Australian Dollar vs Norwegian Krone',
    'AUDNZD' => 'Australian Dollar vs New Zealand Dollar',
    'AUDPLN' => 'Australian Dollar vs Polish Zloty',
    'AUDSEK' => 'Australian Dollar vs Swedish Krona',
    'AUDSGD' => 'Australian Dollar vs Singapore Dollar',
    'AUDTRY' => 'Australian Dollar vs Turkish Lira',
    'AUDUSD' => 'Australian Dollar vs United States Dollar',
    'CADCHF' => 'Canadian Dollar vs Swiss Franc',
    'CADHKD' => 'Canadian Dollar vs Hong Kong Dollar',
    'CADHUF' => 'Canadian Dollar vs Hungarian Forint',
    'CADJPY' => 'Canadian Dollar vs Japanese Yen',
    'CADNOK' => 'Canadian Dollar vs Norwegian Krone',
    'CADPLN' => 'Canadian Dollar vs Polish Zloty',
    'CADSEK' => 'Canadian Dollar vs Swedish Krona',
    'CHFHKD' => 'Swiss Franc vs Hong Kong Dollar',
    'CHFHUF' => 'Swiss Franc vs Hungarian Forint',
    'CHFJPY' => 'Swiss Franc vs Japanese Yen',
    'CHFNOK' => 'Swiss Franc vs Norwegian Krone',
    'CHFPLN' => 'Swiss Franc vs Polish Zloty',
    'CHFSEK' => 'Swiss Franc vs Swedish Krona',
    'EURAUD' => 'Euro vs Australian Dollar',
    'EURCAD' => 'Euro vs Canadian Dollar',
    'EURCHF' => 'Euro vs Swiss Franc',
    'EURCZK' => 'Euro vs Czech Koruna',
    'EURDKK' => 'Euro vs Danish Krone',
    'EURGBP' => 'Euro vs British Pound',
    'EURHKD' => 'Euro vs Hong Kong Dollar',
    'EURHUF' => 'Euro vs Hungarian Forint',
    'EURJPY' => 'Euro vs Japanese Yen',
    'EURNOK' => 'Euro vs Norwegian Krone',
    'EURNZD' => 'Euro vs New Zealand Dollar',
    'EURPLN' => 'Euro vs Polish Zloty',
    'EURSEK' => 'Euro vs Swedish Krona',
    'EURTRY' => 'Euro vs Turkish Lira',
    'EURUSD' => 'Euro vs United States Dollar',
    'GBPAUD' => 'British Pound vs Australian Dollar',
    'GBPCAD' => 'British Pound vs Canadian Dollar',
    'GBPCHF' => 'British Pound vs Swiss Franc',
    'GBPDKK' => 'British Pound vs Danish Krone',
    'GBPHKD' => 'British Pound vs Hong Kong Dollar',
    'GBPHUF' => 'British Pound vs Hungarian Forint',
    'GBPJPY' => 'British Pound vs Japanese Yen',
    'GBPNOK' => 'British Pound vs Norwegian Krone',
    'GBPPLN' => 'British Pound vs Polish Zloty',
    'GBPSEK' => 'British Pound vs Swedish Krona',
    'GBPTRY' => 'British Pound vs Turkish Lira',
    'GBPUSD' => 'British Pound vs United States Dollar',
    'USDCAD' => 'United States Dollar vs Canadian Dollar',
    'USDCHF' => 'United States Dollar vs Swiss Franc',
    'USDCZK' => 'United States Dollar vs Czech Koruna',
    'USDDKK' => 'United States Dollar vs Danish Krone',
    'USDHKD' => 'United States Dollar vs Hong Kong Dollar',
    'USDHUF' => 'United States Dollar vs Hungarian Forint',
    'USDJPY' => 'United States Dollar vs Japanese Yen',
    'USDMXN' => 'United States Dollar vs Mexican Peso',
    'USDNOK' => 'United States Dollar vs Norwegian Krone',
    'USDPLN' => 'United States Dollar vs Polish Zloty',
    'USDSEK' => 'United States Dollar vs Swedish Krona',
    'USDSGD' => 'United States Dollar vs Singapore Dollar',
    'USDTRY' => 'United States Dollar vs Turkish Lira',
    'USDZAR' => 'United States Dollar vs South African Rand',
];

$account = [
    'balance' => 100000.00,
    'equity' => 99999.89,
    'margin' => 13.03,
    'free_margin' => 99986.86,
    'level' => 767458.866
];

$currency_pairs = [
    ['symbol' => 'Volatility 10 (1s) Index', 'bid' => 1245.82, 'ask' => 1245.95, 'change' => 0.23, 'direction' => 'up'],
    ['symbol' => 'Volatility 25 (1s) Index', 'bid' => 2089.45, 'ask' => 2089.62, 'change' => 0.45, 'direction' => 'up'],
    ['symbol' => 'Volatility 50 (1s) Index', 'bid' => 2456.78, 'ask' => 2456.93, 'change' => -0.12, 'direction' => 'down'],
    ['symbol' => 'Volatility 75 (1s) Index', 'bid' => 3569.45, 'ask' => 3569.59, 'change' => 1.34, 'direction' => 'up'],
    ['symbol' => 'Volatility 100 (1s) Index', 'bid' => 5012.30, 'ask' => 5012.45, 'change' => 0.87, 'direction' => 'up'],
    ['symbol' => 'Volatility 10 Index', 'bid' => 1198.56, 'ask' => 1198.67, 'change' => 0.15, 'direction' => 'up'],
    ['symbol' => 'Volatility 25 Index', 'bid' => 2034.21, 'ask' => 2034.35, 'change' => 0.28, 'direction' => 'up'],
    ['symbol' => 'Volatility 50 Index', 'bid' => 2387.92, 'ask' => 2388.05, 'change' => -0.08, 'direction' => 'down'],
    ['symbol' => 'Volatility 75 Index', 'bid' => 3456.78, 'ask' => 3456.91, 'change' => 0.92, 'direction' => 'up'],
    ['symbol' => 'Volatility 100 Index', 'bid' => 4876.34, 'ask' => 4876.48, 'change' => 0.65, 'direction' => 'up'],
];

// Default demo positions now use Synthetic Volatility Indices
$positions = [
    ['symbol' => 'Volatility 75 (1s) Index', 'type' => 'buy', 'volume' => 20, 'open_price' => 3077.89, 'current_price' => 3569.59, 'profit' => 9834.00],
    ['symbol' => 'Volatility 75 (1s) Index', 'type' => 'buy', 'volume' => 20, 'open_price' => 3077.61, 'current_price' => 3569.59, 'profit' => 9839.60],
    ['symbol' => 'Volatility 100 (1s) Index', 'type' => 'buy', 'volume' => 15, 'open_price' => 4521.30, 'current_price' => 5012.45, 'profit' => 7367.25]
];